"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _DataType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _DataTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DataType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Unknown: _DataType.ValueType  # 0
    """Unknown placeholder for future expansion."""

    Int8: _DataType.ValueType  # 1
    """Basic Types"""

    Int16: _DataType.ValueType  # 2
    Int32: _DataType.ValueType  # 3
    Int64: _DataType.ValueType  # 4
    UInt8: _DataType.ValueType  # 5
    UInt16: _DataType.ValueType  # 6
    UInt32: _DataType.ValueType  # 7
    UInt64: _DataType.ValueType  # 8
    Float: _DataType.ValueType  # 9
    Double: _DataType.ValueType  # 10
    Boolean: _DataType.ValueType  # 11
    String: _DataType.ValueType  # 12
    DateTime: _DataType.ValueType  # 13
    Text: _DataType.ValueType  # 14
    UUID: _DataType.ValueType  # 15
    """Additional Metric Types"""

    DataSet: _DataType.ValueType  # 16
    Bytes: _DataType.ValueType  # 17
    File: _DataType.ValueType  # 18
    Template: _DataType.ValueType  # 19
    PropertySet: _DataType.ValueType  # 20
    """Additional PropertyValue Types"""

    PropertySetList: _DataType.ValueType  # 21
    Int8Array: _DataType.ValueType  # 22
    """Array Types"""

    Int16Array: _DataType.ValueType  # 23
    Int32Array: _DataType.ValueType  # 24
    Int64Array: _DataType.ValueType  # 25
    UInt8Array: _DataType.ValueType  # 26
    UInt16Array: _DataType.ValueType  # 27
    UInt32Array: _DataType.ValueType  # 28
    UInt64Array: _DataType.ValueType  # 29
    FloatArray: _DataType.ValueType  # 30
    DoubleArray: _DataType.ValueType  # 31
    BooleanArray: _DataType.ValueType  # 32
    StringArray: _DataType.ValueType  # 33
    DateTimeArray: _DataType.ValueType  # 34
class DataType(_DataType, metaclass=_DataTypeEnumTypeWrapper):
    """Indexes of Data Types"""
    pass

Unknown: DataType.ValueType  # 0
"""Unknown placeholder for future expansion."""

Int8: DataType.ValueType  # 1
"""Basic Types"""

Int16: DataType.ValueType  # 2
Int32: DataType.ValueType  # 3
Int64: DataType.ValueType  # 4
UInt8: DataType.ValueType  # 5
UInt16: DataType.ValueType  # 6
UInt32: DataType.ValueType  # 7
UInt64: DataType.ValueType  # 8
Float: DataType.ValueType  # 9
Double: DataType.ValueType  # 10
Boolean: DataType.ValueType  # 11
String: DataType.ValueType  # 12
DateTime: DataType.ValueType  # 13
Text: DataType.ValueType  # 14
UUID: DataType.ValueType  # 15
"""Additional Metric Types"""

DataSet: DataType.ValueType  # 16
Bytes: DataType.ValueType  # 17
File: DataType.ValueType  # 18
Template: DataType.ValueType  # 19
PropertySet: DataType.ValueType  # 20
"""Additional PropertyValue Types"""

PropertySetList: DataType.ValueType  # 21
Int8Array: DataType.ValueType  # 22
"""Array Types"""

Int16Array: DataType.ValueType  # 23
Int32Array: DataType.ValueType  # 24
Int64Array: DataType.ValueType  # 25
UInt8Array: DataType.ValueType  # 26
UInt16Array: DataType.ValueType  # 27
UInt32Array: DataType.ValueType  # 28
UInt64Array: DataType.ValueType  # 29
FloatArray: DataType.ValueType  # 30
DoubleArray: DataType.ValueType  # 31
BooleanArray: DataType.ValueType  # 32
StringArray: DataType.ValueType  # 33
DateTimeArray: DataType.ValueType  # 34
global___DataType = DataType


class Payload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Template(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        class Parameter(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor
            class ParameterValueExtension(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor
                def __init__(self,
                    ) -> None: ...

            NAME_FIELD_NUMBER: builtins.int
            TYPE_FIELD_NUMBER: builtins.int
            INT_VALUE_FIELD_NUMBER: builtins.int
            LONG_VALUE_FIELD_NUMBER: builtins.int
            FLOAT_VALUE_FIELD_NUMBER: builtins.int
            DOUBLE_VALUE_FIELD_NUMBER: builtins.int
            BOOLEAN_VALUE_FIELD_NUMBER: builtins.int
            STRING_VALUE_FIELD_NUMBER: builtins.int
            EXTENSION_VALUE_FIELD_NUMBER: builtins.int
            name: typing.Text
            type: builtins.int
            int_value: builtins.int
            long_value: builtins.int
            float_value: builtins.float
            double_value: builtins.float
            boolean_value: builtins.bool
            string_value: typing.Text
            @property
            def extension_value(self) -> global___Payload.Template.Parameter.ParameterValueExtension: ...
            def __init__(self,
                *,
                name: typing.Optional[typing.Text] = ...,
                type: typing.Optional[builtins.int] = ...,
                int_value: typing.Optional[builtins.int] = ...,
                long_value: typing.Optional[builtins.int] = ...,
                float_value: typing.Optional[builtins.float] = ...,
                double_value: typing.Optional[builtins.float] = ...,
                boolean_value: typing.Optional[builtins.bool] = ...,
                string_value: typing.Optional[typing.Text] = ...,
                extension_value: typing.Optional[global___Payload.Template.Parameter.ParameterValueExtension] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["boolean_value",b"boolean_value","double_value",b"double_value","extension_value",b"extension_value","float_value",b"float_value","int_value",b"int_value","long_value",b"long_value","name",b"name","string_value",b"string_value","type",b"type","value",b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["boolean_value",b"boolean_value","double_value",b"double_value","extension_value",b"extension_value","float_value",b"float_value","int_value",b"int_value","long_value",b"long_value","name",b"name","string_value",b"string_value","type",b"type","value",b"value"]) -> None: ...
            def WhichOneof(self, oneof_group: typing_extensions.Literal["value",b"value"]) -> typing.Optional[typing_extensions.Literal["int_value","long_value","float_value","double_value","boolean_value","string_value","extension_value"]]: ...

        VERSION_FIELD_NUMBER: builtins.int
        METRICS_FIELD_NUMBER: builtins.int
        PARAMETERS_FIELD_NUMBER: builtins.int
        TEMPLATE_REF_FIELD_NUMBER: builtins.int
        IS_DEFINITION_FIELD_NUMBER: builtins.int
        version: typing.Text
        """The version of the Template to prevent mismatches"""

        @property
        def metrics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Payload.Metric]:
            """Each metric includes a name, datatype, and optionally a value"""
            pass
        @property
        def parameters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Payload.Template.Parameter]: ...
        template_ref: typing.Text
        """MUST be a reference to a template definition if this is an instance (i.e. the name of the template definition) - MUST be omitted for template definitions"""

        is_definition: builtins.bool
        def __init__(self,
            *,
            version: typing.Optional[typing.Text] = ...,
            metrics: typing.Optional[typing.Iterable[global___Payload.Metric]] = ...,
            parameters: typing.Optional[typing.Iterable[global___Payload.Template.Parameter]] = ...,
            template_ref: typing.Optional[typing.Text] = ...,
            is_definition: typing.Optional[builtins.bool] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["is_definition",b"is_definition","template_ref",b"template_ref","version",b"version"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["is_definition",b"is_definition","metrics",b"metrics","parameters",b"parameters","template_ref",b"template_ref","version",b"version"]) -> None: ...

    class DataSet(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        class DataSetValue(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor
            class DataSetValueExtension(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor
                def __init__(self,
                    ) -> None: ...

            INT_VALUE_FIELD_NUMBER: builtins.int
            LONG_VALUE_FIELD_NUMBER: builtins.int
            FLOAT_VALUE_FIELD_NUMBER: builtins.int
            DOUBLE_VALUE_FIELD_NUMBER: builtins.int
            BOOLEAN_VALUE_FIELD_NUMBER: builtins.int
            STRING_VALUE_FIELD_NUMBER: builtins.int
            EXTENSION_VALUE_FIELD_NUMBER: builtins.int
            int_value: builtins.int
            long_value: builtins.int
            float_value: builtins.float
            double_value: builtins.float
            boolean_value: builtins.bool
            string_value: typing.Text
            @property
            def extension_value(self) -> global___Payload.DataSet.DataSetValue.DataSetValueExtension: ...
            def __init__(self,
                *,
                int_value: typing.Optional[builtins.int] = ...,
                long_value: typing.Optional[builtins.int] = ...,
                float_value: typing.Optional[builtins.float] = ...,
                double_value: typing.Optional[builtins.float] = ...,
                boolean_value: typing.Optional[builtins.bool] = ...,
                string_value: typing.Optional[typing.Text] = ...,
                extension_value: typing.Optional[global___Payload.DataSet.DataSetValue.DataSetValueExtension] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["boolean_value",b"boolean_value","double_value",b"double_value","extension_value",b"extension_value","float_value",b"float_value","int_value",b"int_value","long_value",b"long_value","string_value",b"string_value","value",b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["boolean_value",b"boolean_value","double_value",b"double_value","extension_value",b"extension_value","float_value",b"float_value","int_value",b"int_value","long_value",b"long_value","string_value",b"string_value","value",b"value"]) -> None: ...
            def WhichOneof(self, oneof_group: typing_extensions.Literal["value",b"value"]) -> typing.Optional[typing_extensions.Literal["int_value","long_value","float_value","double_value","boolean_value","string_value","extension_value"]]: ...

        class Row(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor
            ELEMENTS_FIELD_NUMBER: builtins.int
            @property
            def elements(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Payload.DataSet.DataSetValue]: ...
            def __init__(self,
                *,
                elements: typing.Optional[typing.Iterable[global___Payload.DataSet.DataSetValue]] = ...,
                ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["elements",b"elements"]) -> None: ...

        NUM_OF_COLUMNS_FIELD_NUMBER: builtins.int
        COLUMNS_FIELD_NUMBER: builtins.int
        TYPES_FIELD_NUMBER: builtins.int
        ROWS_FIELD_NUMBER: builtins.int
        num_of_columns: builtins.int
        @property
        def columns(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
        @property
        def types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def rows(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Payload.DataSet.Row]: ...
        def __init__(self,
            *,
            num_of_columns: typing.Optional[builtins.int] = ...,
            columns: typing.Optional[typing.Iterable[typing.Text]] = ...,
            types: typing.Optional[typing.Iterable[builtins.int]] = ...,
            rows: typing.Optional[typing.Iterable[global___Payload.DataSet.Row]] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["num_of_columns",b"num_of_columns"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["columns",b"columns","num_of_columns",b"num_of_columns","rows",b"rows","types",b"types"]) -> None: ...

    class PropertyValue(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        class PropertyValueExtension(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor
            def __init__(self,
                ) -> None: ...

        TYPE_FIELD_NUMBER: builtins.int
        IS_NULL_FIELD_NUMBER: builtins.int
        INT_VALUE_FIELD_NUMBER: builtins.int
        LONG_VALUE_FIELD_NUMBER: builtins.int
        FLOAT_VALUE_FIELD_NUMBER: builtins.int
        DOUBLE_VALUE_FIELD_NUMBER: builtins.int
        BOOLEAN_VALUE_FIELD_NUMBER: builtins.int
        STRING_VALUE_FIELD_NUMBER: builtins.int
        PROPERTYSET_VALUE_FIELD_NUMBER: builtins.int
        PROPERTYSETS_VALUE_FIELD_NUMBER: builtins.int
        EXTENSION_VALUE_FIELD_NUMBER: builtins.int
        type: builtins.int
        is_null: builtins.bool
        int_value: builtins.int
        long_value: builtins.int
        float_value: builtins.float
        double_value: builtins.float
        boolean_value: builtins.bool
        string_value: typing.Text
        @property
        def propertyset_value(self) -> global___Payload.PropertySet: ...
        @property
        def propertysets_value(self) -> global___Payload.PropertySetList:
            """List of Property Values"""
            pass
        @property
        def extension_value(self) -> global___Payload.PropertyValue.PropertyValueExtension: ...
        def __init__(self,
            *,
            type: typing.Optional[builtins.int] = ...,
            is_null: typing.Optional[builtins.bool] = ...,
            int_value: typing.Optional[builtins.int] = ...,
            long_value: typing.Optional[builtins.int] = ...,
            float_value: typing.Optional[builtins.float] = ...,
            double_value: typing.Optional[builtins.float] = ...,
            boolean_value: typing.Optional[builtins.bool] = ...,
            string_value: typing.Optional[typing.Text] = ...,
            propertyset_value: typing.Optional[global___Payload.PropertySet] = ...,
            propertysets_value: typing.Optional[global___Payload.PropertySetList] = ...,
            extension_value: typing.Optional[global___Payload.PropertyValue.PropertyValueExtension] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["boolean_value",b"boolean_value","double_value",b"double_value","extension_value",b"extension_value","float_value",b"float_value","int_value",b"int_value","is_null",b"is_null","long_value",b"long_value","propertyset_value",b"propertyset_value","propertysets_value",b"propertysets_value","string_value",b"string_value","type",b"type","value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["boolean_value",b"boolean_value","double_value",b"double_value","extension_value",b"extension_value","float_value",b"float_value","int_value",b"int_value","is_null",b"is_null","long_value",b"long_value","propertyset_value",b"propertyset_value","propertysets_value",b"propertysets_value","string_value",b"string_value","type",b"type","value",b"value"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["value",b"value"]) -> typing.Optional[typing_extensions.Literal["int_value","long_value","float_value","double_value","boolean_value","string_value","propertyset_value","propertysets_value","extension_value"]]: ...

    class PropertySet(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEYS_FIELD_NUMBER: builtins.int
        VALUES_FIELD_NUMBER: builtins.int
        @property
        def keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
            """Names of the properties"""
            pass
        @property
        def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Payload.PropertyValue]: ...
        def __init__(self,
            *,
            keys: typing.Optional[typing.Iterable[typing.Text]] = ...,
            values: typing.Optional[typing.Iterable[global___Payload.PropertyValue]] = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["keys",b"keys","values",b"values"]) -> None: ...

    class PropertySetList(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        PROPERTYSET_FIELD_NUMBER: builtins.int
        @property
        def propertyset(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Payload.PropertySet]: ...
        def __init__(self,
            *,
            propertyset: typing.Optional[typing.Iterable[global___Payload.PropertySet]] = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["propertyset",b"propertyset"]) -> None: ...

    class MetaData(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        IS_MULTI_PART_FIELD_NUMBER: builtins.int
        CONTENT_TYPE_FIELD_NUMBER: builtins.int
        SIZE_FIELD_NUMBER: builtins.int
        SEQ_FIELD_NUMBER: builtins.int
        FILE_NAME_FIELD_NUMBER: builtins.int
        FILE_TYPE_FIELD_NUMBER: builtins.int
        MD5_FIELD_NUMBER: builtins.int
        DESCRIPTION_FIELD_NUMBER: builtins.int
        is_multi_part: builtins.bool
        """Bytes specific metadata"""

        content_type: typing.Text
        """General metadata
        Content/Media type
        """

        size: builtins.int
        """File size, String size, Multi-part size, etc"""

        seq: builtins.int
        """Sequence number for multi-part messages"""

        file_name: typing.Text
        """File metadata
        File name
        """

        file_type: typing.Text
        """File type (i.e. xml, json, txt, cpp, etc)"""

        md5: typing.Text
        """md5 of data"""

        description: typing.Text
        """Catchalls and future expansion
        Could be anything such as json or xml of custom properties
        """

        def __init__(self,
            *,
            is_multi_part: typing.Optional[builtins.bool] = ...,
            content_type: typing.Optional[typing.Text] = ...,
            size: typing.Optional[builtins.int] = ...,
            seq: typing.Optional[builtins.int] = ...,
            file_name: typing.Optional[typing.Text] = ...,
            file_type: typing.Optional[typing.Text] = ...,
            md5: typing.Optional[typing.Text] = ...,
            description: typing.Optional[typing.Text] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["content_type",b"content_type","description",b"description","file_name",b"file_name","file_type",b"file_type","is_multi_part",b"is_multi_part","md5",b"md5","seq",b"seq","size",b"size"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["content_type",b"content_type","description",b"description","file_name",b"file_name","file_type",b"file_type","is_multi_part",b"is_multi_part","md5",b"md5","seq",b"seq","size",b"size"]) -> None: ...

    class Metric(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        class MetricValueExtension(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor
            def __init__(self,
                ) -> None: ...

        NAME_FIELD_NUMBER: builtins.int
        ALIAS_FIELD_NUMBER: builtins.int
        TIMESTAMP_FIELD_NUMBER: builtins.int
        DATATYPE_FIELD_NUMBER: builtins.int
        IS_HISTORICAL_FIELD_NUMBER: builtins.int
        IS_TRANSIENT_FIELD_NUMBER: builtins.int
        IS_NULL_FIELD_NUMBER: builtins.int
        METADATA_FIELD_NUMBER: builtins.int
        PROPERTIES_FIELD_NUMBER: builtins.int
        INT_VALUE_FIELD_NUMBER: builtins.int
        LONG_VALUE_FIELD_NUMBER: builtins.int
        FLOAT_VALUE_FIELD_NUMBER: builtins.int
        DOUBLE_VALUE_FIELD_NUMBER: builtins.int
        BOOLEAN_VALUE_FIELD_NUMBER: builtins.int
        STRING_VALUE_FIELD_NUMBER: builtins.int
        BYTES_VALUE_FIELD_NUMBER: builtins.int
        DATASET_VALUE_FIELD_NUMBER: builtins.int
        TEMPLATE_VALUE_FIELD_NUMBER: builtins.int
        EXTENSION_VALUE_FIELD_NUMBER: builtins.int
        name: typing.Text
        """Metric name - should only be included on birth"""

        alias: builtins.int
        """Metric alias - tied to name on birth and included in all later DATA messages"""

        timestamp: builtins.int
        """Timestamp associated with data acquisition time"""

        datatype: builtins.int
        """DataType of the metric/tag value"""

        is_historical: builtins.bool
        """If this is historical data and should not update real time tag"""

        is_transient: builtins.bool
        """Tells consuming clients such as MQTT Engine to not store this as a tag"""

        is_null: builtins.bool
        """If this is null - explicitly say so rather than using -1, false, etc for some datatypes."""

        @property
        def metadata(self) -> global___Payload.MetaData:
            """Metadata for the payload"""
            pass
        @property
        def properties(self) -> global___Payload.PropertySet: ...
        int_value: builtins.int
        long_value: builtins.int
        float_value: builtins.float
        double_value: builtins.float
        boolean_value: builtins.bool
        string_value: typing.Text
        bytes_value: builtins.bytes
        """Bytes, File"""

        @property
        def dataset_value(self) -> global___Payload.DataSet: ...
        @property
        def template_value(self) -> global___Payload.Template: ...
        @property
        def extension_value(self) -> global___Payload.Metric.MetricValueExtension: ...
        def __init__(self,
            *,
            name: typing.Optional[typing.Text] = ...,
            alias: typing.Optional[builtins.int] = ...,
            timestamp: typing.Optional[builtins.int] = ...,
            datatype: typing.Optional[builtins.int] = ...,
            is_historical: typing.Optional[builtins.bool] = ...,
            is_transient: typing.Optional[builtins.bool] = ...,
            is_null: typing.Optional[builtins.bool] = ...,
            metadata: typing.Optional[global___Payload.MetaData] = ...,
            properties: typing.Optional[global___Payload.PropertySet] = ...,
            int_value: typing.Optional[builtins.int] = ...,
            long_value: typing.Optional[builtins.int] = ...,
            float_value: typing.Optional[builtins.float] = ...,
            double_value: typing.Optional[builtins.float] = ...,
            boolean_value: typing.Optional[builtins.bool] = ...,
            string_value: typing.Optional[typing.Text] = ...,
            bytes_value: typing.Optional[builtins.bytes] = ...,
            dataset_value: typing.Optional[global___Payload.DataSet] = ...,
            template_value: typing.Optional[global___Payload.Template] = ...,
            extension_value: typing.Optional[global___Payload.Metric.MetricValueExtension] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["alias",b"alias","boolean_value",b"boolean_value","bytes_value",b"bytes_value","dataset_value",b"dataset_value","datatype",b"datatype","double_value",b"double_value","extension_value",b"extension_value","float_value",b"float_value","int_value",b"int_value","is_historical",b"is_historical","is_null",b"is_null","is_transient",b"is_transient","long_value",b"long_value","metadata",b"metadata","name",b"name","properties",b"properties","string_value",b"string_value","template_value",b"template_value","timestamp",b"timestamp","value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["alias",b"alias","boolean_value",b"boolean_value","bytes_value",b"bytes_value","dataset_value",b"dataset_value","datatype",b"datatype","double_value",b"double_value","extension_value",b"extension_value","float_value",b"float_value","int_value",b"int_value","is_historical",b"is_historical","is_null",b"is_null","is_transient",b"is_transient","long_value",b"long_value","metadata",b"metadata","name",b"name","properties",b"properties","string_value",b"string_value","template_value",b"template_value","timestamp",b"timestamp","value",b"value"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["value",b"value"]) -> typing.Optional[typing_extensions.Literal["int_value","long_value","float_value","double_value","boolean_value","string_value","bytes_value","dataset_value","template_value","extension_value"]]: ...

    TIMESTAMP_FIELD_NUMBER: builtins.int
    METRICS_FIELD_NUMBER: builtins.int
    SEQ_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    timestamp: builtins.int
    """Timestamp at message sending time"""

    @property
    def metrics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Payload.Metric]:
        """Repeated forever - no limit in Google Protobufs"""
        pass
    seq: builtins.int
    """Sequence number"""

    uuid: typing.Text
    """UUID to track message type in terms of schema definitions"""

    body: builtins.bytes
    """To optionally bypass the whole definition above"""

    def __init__(self,
        *,
        timestamp: typing.Optional[builtins.int] = ...,
        metrics: typing.Optional[typing.Iterable[global___Payload.Metric]] = ...,
        seq: typing.Optional[builtins.int] = ...,
        uuid: typing.Optional[typing.Text] = ...,
        body: typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["body",b"body","seq",b"seq","timestamp",b"timestamp","uuid",b"uuid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["body",b"body","metrics",b"metrics","seq",b"seq","timestamp",b"timestamp","uuid",b"uuid"]) -> None: ...
global___Payload = Payload
